# Generated by Django 4.0.5 on 2022-06-22 07:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zwrot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=256)),
                ('nazwisko', models.CharField(max_length=256)),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('towar', models.TextField()),
                ('dowod_zakupu', models.CharField(max_length=128)),
                ('cena_zakupu', models.FloatField()),
                ('dane_do_zwrotu', models.CharField(max_length=128)),
                ('data_odebrania_towaru', models.DateField(auto_now=True)),
            ],
        ),
    ]
