# Generated by Django 4.0.5 on 2022-06-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_zwrot_data_odebrania_towaru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zwrot',
            old_name='dowod_zakupu',
            new_name='faktura',
        ),
        migrations.AddField(
            model_name='zwrot',
            name='paragon',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='dane_do_zwrotu',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
