# Generated by Django 4.0.5 on 2022-06-22 08:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dowod_zakupu_zwrot_faktura_zwrot_paragon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwrot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+48', max_length=128, region=None),
        ),
    ]
