# Generated by Django 4.0.5 on 2022-06-22 08:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_zwrot_id_alter_zwrot_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwrot',
            name='cena_zakupu',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='data_odebrania_towaru',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+48', max_length=128, region=None),
        ),
    ]
