# Generated by Django 4.0.5 on 2022-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_zwrot_cena_zakupu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zwrot',
            name='powod_zwrotu',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
