# Generated by Django 4.0.5 on 2022-06-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_zwrot_powod_zwrotu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwrot',
            name='cena_zakupu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='powod_zwrotu',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
