# Generated by Django 4.0.5 on 2022-06-22 08:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_zwrot_cena_zakupu_alter_zwrot_powod_zwrotu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwrot',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='+48'),
        ),
    ]
