# Generated by Django 4.0.5 on 2022-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_zwrot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zwrot',
            name='dane_do_zwrotu_str',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
