# Generated by Django 4.0.5 on 2022-06-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_zwrot_dane_do_zwrotu_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='zwrot',
            name='data_zwrotu_pieniedzy',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='data_odebrania_towaru',
            field=models.DateField(auto_created=True),
        ),
    ]
