# Generated by Django 4.0.5 on 2022-06-23 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_zwrot_data_odebrania_towaru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwrot',
            name='data_zwrotu_pieniedzy',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
