# Generated by Django 4.0.5 on 2022-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_zwrot_data_zwrotu_pieniedzy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwrot',
            name='data_odebrania_towaru',
            field=models.DateField(blank=True, null=True),
        ),
    ]
