# Generated by Django 4.0.5 on 2022-06-23 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_zwrot_data_odebrania_towaru'),
    ]

    operations = [
        migrations.AddField(
            model_name='zwrot',
            name='data_zwrotu_pieniedzy',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zwrot',
            name='data_odebrania_towaru',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
