# Generated by Django 4.0.5 on 2022-06-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_zwrot_data_zwrotu_pieniedzy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zwrot',
            old_name='dane_do_zwrotu_str',
            new_name='numer_konta',
        ),
    ]
