# Generated by Django 4.0.5 on 2022-06-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_zwrot_data_zwrotu_pieniedzy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zwrot',
            name='data_zwrotu_pieniedzy',
        ),
    ]
